import { z } from 'zod'
import { MAX_REMARKS_LENGTH } from '@/components/document/DocumentOtherFields'

export const companyFormSchema = z.object({
    companyNo: z.string().optional(),
    companyName: z.string().min(1, '必須です'),
    companyAddress: z.string().min(1, '必須です'),
    companyTel: z.string().min(1, '必須です'),
    companyFax: z.string().optional(),
    repTitle: z.string().optional(),
    repName: z.string().optional(),
    bank1Name: z.string().optional(),
    bank1Branch: z.string().optional(),
    bank1Type: z.string().optional(),
    bank1Account: z.string().optional(),
    bank1Holder: z.string().optional(),
    bank2Name: z.string().optional(),
    bank2Branch: z.string().optional(),
    bank2Type: z.string().optional(),
    bank2Account: z.string().optional(),
    bank2Holder: z.string().optional(),
    bank3Name: z.string().optional(),
    bank3Branch: z.string().optional(),
    bank3Type: z.string().optional(),
    bank3Account: z.string().optional(),
    bank3Holder: z.string().optional(),
    bank4Name: z.string().optional(),
    bank4Branch: z.string().optional(),
    bank4Type: z.string().optional(),
    bank4Account: z.string().optional(),
    bank4Holder: z.string().optional(),
    dateFormat: z.enum(['WESTERN', 'JAPANESE']),
    pdfShowOptionImages: z.boolean(),
    pdfPromptOnExport: z.boolean(),
    pdfShowFreeItemUnitPrice: z.boolean(),
    pdfShowFreeItemQty: z.boolean(),
    estimateRemarksDefault: z.string().max(MAX_REMARKS_LENGTH, `${MAX_REMARKS_LENGTH}文字以内で入力してください`).optional(),
    invoiceRemarksDefault: z.string().max(MAX_REMARKS_LENGTH, `${MAX_REMARKS_LENGTH}文字以内で入力してください`).optional(),
    sealImageUrl: z.string().optional(),
})

export type CompanyFormData = z.infer<typeof companyFormSchema>

export const DEFAULT_FORM_VALUES: CompanyFormData = {
    companyNo: '',
    companyName: '',
    companyAddress: '',
    companyTel: '',
    companyFax: '',
    repTitle: '',
    repName: '',
    bank1Name: '',
    bank1Branch: '',
    bank1Type: '',
    bank1Account: '',
    bank1Holder: '',
    bank2Name: '',
    bank2Branch: '',
    bank2Type: '',
    bank2Account: '',
    bank2Holder: '',
    bank3Name: '',
    bank3Branch: '',
    bank3Type: '',
    bank3Account: '',
    bank3Holder: '',
    bank4Name: '',
    bank4Branch: '',
    bank4Type: '',
    bank4Account: '',
    bank4Holder: '',
    dateFormat: 'WESTERN',
    pdfShowOptionImages: false,
    pdfPromptOnExport: true,
    pdfShowFreeItemUnitPrice: true,
    pdfShowFreeItemQty: true,
    estimateRemarksDefault: '',
    invoiceRemarksDefault: '',
    sealImageUrl: '',
}
