export const MATURITY_SERVICE_NAME = '満期サービス'
export const CANCELLATION_FEE_NAME = '解約手数料'

type DocumentFreeItemBase = {
    parentProductItemId?: string | null
    productItemName: string
    description?: string
    unitPriceGeneral: number
    qty: number
    amount: number
    sortNo?: number
}

const FIXED_FREE_ROW_COUNT = 5

// フリー行を 5 行に揃え、末尾に fixedRowNames の固定行を順番に追加する。
// 既存データがあれば引き継ぎ、なければ初期値で生成。摘要は固定行では常に空にする。
export function padDocumentFreeItems<T extends DocumentFreeItemBase>(
    arr: T[],
    fixedRowNames: string[]
): T[] {
    const fixedSet = new Set(fixedRowNames)
    const others = arr.filter((it) => !fixedSet.has(it.productItemName))

    const padded: T[] = others.slice()
    while (padded.length < FIXED_FREE_ROW_COUNT) {
        padded.push({ productItemName: '', description: '', unitPriceGeneral: 0, qty: 0, amount: 0, sortNo: padded.length } as T)
    }

    fixedRowNames.forEach((name, idx) => {
        const existing = arr.find((it) => it.productItemName === name)
        padded.push(
            existing
                ? { ...existing, description: '', sortNo: FIXED_FREE_ROW_COUNT + idx }
                : { productItemName: name, description: '', unitPriceGeneral: 0, qty: 0, amount: 0, sortNo: FIXED_FREE_ROW_COUNT + idx } as T
        )
    })

    return padded
}

export function sortByProductItemId<T extends { productItemId?: string | null }>(arr: T[]): T[] {
    return arr.slice().sort((a, b) => {
        if (a.productItemId == null) return 1
        if (b.productItemId == null) return -1
        return Number(a.productItemId) - Number(b.productItemId)
    })
}

// EACH モード（isMultiSelect=true, multiSelectMerge=false）の明細行を
// バリアントごとに複数行へ展開し、sortNo を振り直して返す
export function expandEachModeItems<T extends { qty: number; multiSelectVariantIds?: string | null; [key: string]: any }>(
    activeItems: T[],
    isMember: boolean
): T[] {
    return activeItems.flatMap((item) => {
        const pi = item.productItem
        if (!pi?.isMultiSelect || pi.multiSelectMerge !== false) return [item]
        if (!item.multiSelectVariantIds) return [item]
        try {
            const ids: string[] = JSON.parse(item.multiSelectVariantIds)
            if (ids.length === 0) return [item]
            return ids.flatMap((variantId: string) => {
                const v = (pi.variants || []).find((v: any) => String(v.id) === variantId)
                if (!v) return []
                return [{ ...item, productVariantId: String(v.id), productVariant: v,
                    unitPriceGeneral: v.priceGeneral, unitPriceMember: v.priceMember,
                    amount: (isMember ? v.priceMember : v.priceGeneral) * item.qty,
                    multiSelectVariantIds: null, description: v.name }]
            })
        } catch { return [item] }
    }).map((item, i) => ({ ...item, sortNo: i }))
}

// フリー行を親付き/親なしに分離し、パディング・自動生成を行って結合して返す
// fixedRowNames: 末尾に固定配置する行名（見積: [満期サービス]、請求書: [満期サービス, 解約手数料]）
export function buildDocumentFreeItems<T extends DocumentFreeItemBase>(
    loadedFreeItems: T[],
    mergedItems: Array<{ qty?: number | null; productItem?: any }>,
    fixedRowNames: string[]
): T[] {
    const standaloneFreeItems = loadedFreeItems.filter((fi) => !fi.parentProductItemId)
    const parentLinkedFreeItems = loadedFreeItems.filter((fi) => fi.parentProductItemId)

    const paddedStandaloneFreeItems = padDocumentFreeItems(standaloneFreeItems, fixedRowNames)

    const existingParentIds = new Set(
        parentLinkedFreeItems.map((fi) => String(fi.parentProductItemId))
    )
    const autoGeneratedFreeItems: T[] = []
    for (const item of mergedItems) {
        if (!item.qty || item.qty <= 0) continue
        const product = item.productItem as any
        if (!product?.canAddFreeRow) continue
        const pid = String(product.id)
        if (existingParentIds.has(pid)) continue
        autoGeneratedFreeItems.push({
            parentProductItemId: pid,
            productItemName: '',
            description: '',
            unitPriceGeneral: 0,
            qty: 0,
            amount: 0,
            sortNo: 9999,
        } as T)
    }

    return [
        ...paddedStandaloneFreeItems,
        ...parentLinkedFreeItems,
        ...autoGeneratedFreeItems,
    ]
}

// docNo 採番: reception_at の年月（yyyymm）プレフィックスを返す
export function buildDocNoPrefix(receptionAt: Date | string | null | undefined): string {
    const date = receptionAt ? new Date(receptionAt) : new Date()
    const yyyy = date.getFullYear()
    const mm = String(date.getMonth() + 1).padStart(2, '0')
    return `${yyyy}${mm}`
}

// docNo 採番: プレフィックスと最新 docNo から次の連番 docNo を返す
// override が指定されている場合（フォームから送られてきた値）はそちらを優先する
export function buildDocNo(prefix: string, latestDocNo: string | null | undefined, override?: string): string {
    if (override) return override
    const nextSeq = latestDocNo ? parseInt(latestDocNo.slice(6)) + 1 : 1
    return `${prefix}${String(nextSeq).padStart(3, '0')}`
}
